apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archagent-collector-credential
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.credential.storage }}
